### ISSUE TITLE
This doesn't work with scheduled deployment

### ISSUE THREAD

**Issue by WhisperFan** [amanbedi18/CreateBug-VSTS-Task#1]
I used this extension in a scheduled release pipeline which runs every night. And I got 400 bad request. I assume it's because the requester is empty in this case. 

When I remove the schedule and deploy it manually, the extension works.

Would it be possible to add the functionality of dealing with scheduled deployment? 

Maybe one of options is to make $Requestor an input from users.

**Comment by amanbedi18** [comment]
@WhisperFan Thanks for the suggestion, I have added an option to provide custom identity for the release requestor as an input. Check custom requestor flag in task settings to enable it. Update your task to v2 in the target pipeline. Here is v2 documentation to configure custom requestor: https://marketplace.visualstudio.com/items?itemName=AmanBedi18.CreateBugTask
