### ISSUE TITLE
TFS 2015.2 support

### ISSUE THREAD

**Issue by MrRodrigoAntunes** [amanbedi18/CreateBug-VSTS-Task#2]
Hi,
Does it work with TFS 2015 Update 2?
Looking into the source code it doesn't seem to support. Can you confirm?

I'm stating this based on the API version:
"$uri = "$vstsUri$teamProject/_apis/Release/releases/$($ReleaseId)?**api-version=3.0-preview.1**"

And the public documentation regarding TFS 2015.2 available APIs:
[Release Management](https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/rm/overview?view=vsts)
"Using on-premises: An earlier, and slightly different, version of this Release Management API is available in Team Foundation Server 2015 Update 2. To use, you must specify an API version of 2.2-preview.1."

Thank you,
Rodrigo

**Comment by amanbedi18** [comment]
Hello @MrRodrigoAntunes, there are no plans to support TFS on premise but if you want to reuse the script that has implemented these API's in the task, feel free to modify and customize it to implement TFS related API's and run the script as a PowerShell task in your pipelines.
In case your team has moved to ADO organization model, you can now use v2 of the task for the same.
