### ISSUE TITLE
Yaml pipelines are build pipelines - so 404 by GetRelease 

### ISSUE THREAD

**Issue by svsvirid** [amanbedi18/CreateBug-VSTS-Task#5]
This line doesn't work for yaml pipelines, as they only get a Build ID:
$uri = "$vstsUri$teamProject/_apis/Release/releases/$($ReleaseId)?api-version=3.0-preview.1"
Write-Host "Invoking Rest Endpoint to get current release details: $uri"

Buld Get API call should be used instead: https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/get?view=azure-devops-rest-5.0

**Comment by amanbedi18** [comment]
@svsvirid just released v2 of this task which now supports multi-stage YAML pipelines. Needs some additional steps to enable OAuth token and check "isYAML" flag in the task config to make this work with different set of API's. You can find the documentation for the same at https://marketplace.visualstudio.com/items?itemName=AmanBedi18.CreateBugTask
Test it out and let me know how it goes :)
