### ISSUE TITLE
Iteration path does not support @CurrentIteration

### ISSUE THREAD

**Issue by timmkrause** [amanbedi18/CreateBug-VSTS-Task#6]
We have to provide custom area and iteration paths.

Would it be possible to add support for the `@CurrentIteration` variable which is supported by Azure DevOps (or any other dynamic way)?

Changing the Release Pipeline regarding this parameter for every sprint would not really be an elegant solution.

Thank you so much so far for providing this extension.

**Comment by timmkrause** [comment]
Is this project alive?

**Comment by amanbedi18** [comment]
@timmkrause the default behavior of the task already uses current area and iteration path of the team project to which the pipeline belongs to. You do not need to provide custom path and change it for every sprint!

**Comment by amanbedi18** [comment]
> Is this project alive?

Yes, here is changelog for v2 which now also supports YAML pipelines: https://marketplace.visualstudio.com/items?itemName=AmanBedi18.CreateBugTask
